### ISSUE TITLE
Incompatible @intlify/vue-router-bridge and vue-i18n-routing

### ISSUE THREAD

**Issue by padinko** [intlify/bridging#49]
### Clear and concise description of the problem

Hello,
i18n for nuxt3 `@nuxtjs/i18n@next` requires `vue-i18n-routing` and this modules requires `@intlify/vue-router-bridge` from this repo

problem is 
`vue-i18n-routing` requires `"vue-demi": "^0.14.5"`
but `@intlify/vue-router-bridge` requires `"vue-demi": "^0.13.5"`

in npm `^` means: update until first non zero version number will change; so with package with zero major (first) version only patch (third) version can update

and this incompatibility cause issues in installing nuxt project with i18n at all
see
https://github.com/nuxt-modules/i18n/issues/1640
https://github.com/nuxt-modules/i18n/issues/2556
and many more issues

### Suggested solution

i found this commit https://github.com/intlify/bridging/commit/82ef441d9fb79aacd1087b1ecb8c10cf98c9121a already updated `vue-demi` to `^0.14` which will fix issues

can you release new version of @intlify/vue-router-bridge with this change?

### Alternative

maybe you can use `~0.13` instead of `^0.13`
`~` means that only major (first) version can not change in update, and then ^0.14 and ~0.13 will be compatible

### Validations

- [X] Follow our [Code of Conduct](https://github.com/intlify/bridging/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/intlify/bridging/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kazupon** [comment]
close, so released with #50
